### ISSUE TITLE
[Request]: Optimize and decrease the snap size

### ISSUE THREAD

**Issue by soumyaDghosh** [GeopJr/Tuba#186]
### Describe the request

Use this snapcraft.yaml instead of the current
````
name: tuba
base: core22
version: git
adopt-info: tuba

grade: devel
confinement: strict
license: GPL-3.0-only
compression: lzo

slots:
  tuba:
    interface: dbus
    bus: session
    name: dev.geopjr.Tuba

apps:
  tuba:
    command: usr/bin/dev.geopjr.Tuba
    desktop: usr/share/applications/dev.geopjr.Tuba.desktop
    common-id: dev.geopjr.Tuba.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - network-status
      - gsettings
      - network

parts:
  tuba:
    source: .
    source-type: git
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Ddevel=true
    parse-info: [usr/share/metainfo/dev.geopjr.Tuba.appdata.xml]
    build-packages:
      - libjson-glib-dev
      - libsecret-1-dev
``````

Packages like `ibadwaita`, `libgtk4`, `gtksourceview` all are available in the gnome-extension, So, no need of them

### Implementation Details

- [X] This should be an option in settings.
- [X] This should be only available to some fediverse backends. (Include which ones on the above field).
- [X] This is client-only (and shouldn't sync with the instance).
- [X] This follows the [GNOME HIG](https://developer.gnome.org/hig/).
