### ISSUE TITLE
Better symbolic icon for link previews w/o image?

### ISSUE THREAD

**Issue by bertob** [GeopJr/Tuba#573]
Currently we use a document icon for articles without an image, which doesn't look great or add much. I'd replace it with an icon that gets the "website" idea across better (e.g. `earth-symbolic`?), or maybe no icon at all.

![image](https://github.com/GeopJr/Tuba/assets/1908896/444035a2-e266-4336-8655-61bd9f66fc55)

**Comment by bertob** [comment]
Elk adds a different background color, which would definitely help make the small icon feel more balanced in this layout. If we keep an icon I'd do this here as well.

![image](https://github.com/GeopJr/Tuba/assets/1908896/b2398194-2d22-47a3-84cf-e5d75f275b39)

**Comment by GeopJr** [comment]
1. Background on both
![Screenshot from 2023-10-02 05-49-09](https://github.com/GeopJr/Tuba/assets/18014039/1b54d78f-190a-4da9-9cca-6823db4c28d3)
2. Background only on earth
![Screenshot from 2023-10-02 05-48-50](https://github.com/GeopJr/Tuba/assets/18014039/fcd22ee9-69be-47d0-a04d-47e467e35768)
3. No earth
![Screenshot from 2023-10-02 05-43-46](https://github.com/GeopJr/Tuba/assets/18014039/1fbe9337-21d2-460b-b04c-8ec1bcd11192)
4. Just earth
![Screenshot from 2023-10-02 05-43-40](https://github.com/GeopJr/Tuba/assets/18014039/075e89e7-0ddf-4802-b926-ea7039941807)

Video preview cards use the play icon, should that change?

![Screenshot from 2023-10-02 05-43-02](https://github.com/GeopJr/Tuba/assets/18014039/23714b06-fa8f-441a-8276-08bc1e2ed182)

**Comment by LukaszH77** [comment]
I think I like 2nd one the most with 1st being close behind.

**Comment by bertob** [comment]
I'd go with something between 1 and 2, i.e. a little bit of a background on both, but a bit less opaque than on 1.

**Comment by GeopJr** [comment]
default:
![Screenshot from 2023-10-02 20-13-59](https://github.com/GeopJr/Tuba/assets/18014039/da3d5b37-2717-462e-9c5f-1fecebbe4d8a)
![Screenshot from 2023-10-02 20-23-20](https://github.com/GeopJr/Tuba/assets/18014039/ed7891ab-9332-488b-9cdc-8d3334357298)


hover:
![Screenshot from 2023-10-02 20-14-09](https://github.com/GeopJr/Tuba/assets/18014039/7446eeec-b46c-4646-9075-3828b02a6983)
![Screenshot from 2023-10-02 20-23-24](https://github.com/GeopJr/Tuba/assets/18014039/b409f948-d912-42d0-a1de-beaf62abbbdb)

note: the hover screenshot above uses #583 / #581, it might look a bit different without it

the style is:
```scss
// light
.preview_card:not(.explore), .preview_card:not(.explore) image:not(.attachment-overlay-icon) {
	background-color: rgba(0,0,0,0.05);
}

.preview_card:not(.explore):hover {
	background-color: rgba(0,0,0,0.1);
}


// dark
.preview_card:not(.explore), .preview_card:not(.explore) image:not(.attachment-overlay-icon) {
	background-color: rgba(255,255,255,0.05);
}

.preview_card:not(.explore):hover {
	background-color: rgba(255,255,255,0.1);
}
```

any notes?

**Comment by GeopJr** [comment]
Sounds good to me! Should we drop the frame from all post widgets? (media, polls, cards)

frame:
![Screenshot from 2023-10-02 21-56-44](https://github.com/GeopJr/Tuba/assets/18014039/bd86564f-9486-4b4c-8df8-0d14ba68ac0b)

without frame:
![Screenshot from 2023-10-02 21-57-50](https://github.com/GeopJr/Tuba/assets/18014039/05eb58ad-a234-462a-ba42-d23b25e7ca5f)

polls need the frame however:
|||
|:---:|:---:|
| ![Screenshot from 2023-10-02 21-58-48](https://github.com/GeopJr/Tuba/assets/18014039/f4e22cc7-cde9-46d5-896b-f84ad50c5705) | ![Screenshot from 2023-10-02 21-58-56](https://github.com/GeopJr/Tuba/assets/18014039/f41c7e7b-9e46-4e94-aa2b-cf975367bb58) |

**Comment by bertob** [comment]
I guess with media it's trickier since we don't control the background. Maybe a very slight border makes sense there.

As for polls, yes, dropping the border would require redesigning them a bit. Maybe the bars could have a slight gray background and have a bit of vertical padding between each row instead of being grouped?

**Comment by GeopJr** [comment]
I'm afraid preview cards will also suffer from that since the preview images can have a white background too. The `.frame` style if from GTK

```scss
.frame {
  border: 1px solid $borders_color;
}
```

We could make it less noticeable or use shadows:

![image](https://github.com/GeopJr/Tuba/assets/18014039/458ea7d1-db75-42aa-baf4-6a11ca316e30)

As for polls, it might be worth to wait a bit until the accent colors land so we figure out accessibility, I'm already not happy with some of Ubuntu's accents:

![image](https://github.com/GeopJr/Tuba/assets/18014039/e8be678a-903f-4a37-9f37-8568035f0837)
